# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 1.0.2
# Disable/Enable Command Modules:
# Useful if you don't want a certain command on your server or if another mod handles a certain command
Commands:
  anvil: true
  ascend: true
  back: true
  clearinventory: true
  hat: true
  home: true # Contains /home, /homes, /sethome, /delhome, /home:
  descend: true
  disposal: true
  enderchest: true
  feed: true
  fly: true
  gm: true  # Contains /gma, /gmc, /gms, /gmsp
  grindstone: true
  heal: true
  ignore: true
  message: true # Contains /msg, /reply, /socialspy
  playtime: true
  repair: true
  rtp: true
  biomertp: true
  seen: true
  smite: true
  smithing: true
  spawn: true # Contains /spawn, /setspawn
  speed: true
  stonecutter: true
  textcommands: true
  time: true
  tp: true # contains /tphere, /tpoffline
  tpa: true # Contains /tpa, /tpahere, /tpaccept, /tpdeny, /tpacancel
  top: true
  warp: true # Contains /warp, /warps, /setwarp, /delwarp
  workbench: true
Unsafe-Blocks:
# These are used in multiple commands, such as RTP, Top, Ascend, and Descend.
# These commands will never let the player land on or in these blocks.
  - "minecraft:lava"
  - "minecraft:cactus"
  - "minecraft:bedrock"
Air-Blocks:
# These are the blocks that teleports will see as air.
  - "minecraft:air"
  - "minecraft:void_air"
  - "minecraft:cave_air"
Hat:
  # Items the player may not put on their head via /hat.
  Blacklisted-Items:
    - "minecraft:barrier" # This stops all barriers from being placed on the player's head.
    - "minecraft:diamond_sword:1" # This stops diamond swords with a CustomModelData of 1 from being put on the player's head.
Repair:
  # Items the player may not repair
  Blacklisted-Items:
    - "minecraft:wooden_axe"
    - "minecraft:wooden_axe:1"
# Migrate data from other mods into EEssentials
# By default, this will be off. Set to True to enable importing
Importers:
  EssentialCommands: false