# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 1.0.1
# Disable/Enable Command Modules:
# Useful if you don't want a certain command on your server or if another mod handles a certain command
Commands:
  anvil: true
  ascend: true
  back: true
  clearinventory: true
  hat: true
  home: true # Contains /home, /homes, /sethome, /delhome, /home:
  descend: true
  disposal: true
  enderchest: true
  feed: true
  fly: true
  gm: true  # Contains /gma, /gmc, /gms, /gmsp
  grindstone: true
  heal: true
  ignore: true
  message: true # Contains /msg, /reply, /socialspy
  playtime: true
  repair: true
  rtp: true
  seen: true
  smite: true
  smithing: true
  spawn: true # Contains /spawn, /setspawn
  speed: true
  stonecutter: true
  textcommands: true
  time: true
  tp: true # contains /tphere, /tpoffline
  tpa: true # Contains /tpa, /tpahere, /tpaccept, /tpdeny, /tpacancel
  top: true
  warp: true # Contains /warp, /warps, /setwarp, /delwarp
  workbench: true
Random-Teleport:
  Max-Attempts: 10
  # How many attempts the plugin will take to find a safe location for a player to teleport to before giving up.
  Worlds:
    "minecraft:overworld":
    # You can change the world names to whatever you'd like, they're only visual, however changing them requires a server reboot.
    # Any worlds not here will automatically be blacklisted. Case sensitive.
      Min-Distance: 250
      # The minimum distance from 0, 0 the random location must be.
      # (I.E. if this is set to 250, your x and z coordinates MUST each be higher than 250.
      Max-Distance: 5000
      # The maximum distance from 0, 0 the random location must be.
      # (I.E. if this is set to 5000, your x and z coordinates may not go higher than 5000.
      Cooldown: 60
      # The cooldown on random teleporting in this world, in seconds.
      Allow-Cave-Teleports: false
      # If true, players may randomly teleport into underground caves.
      # Otherwise, it'll always land the player on the highest block exposed to air.
      # If this is a nether world, set this to true.
      Highest-Y: 320
      # The highest Y the teleport may be.
      # Suggested 127 for nether worlds to not allow players on the roof, 320 for anything else.
    "minecraft:the_nether":
      Redirect-To: "minecraft:overworld"
      # Redirects this world's random teleports to the target world.
    "minecraft:the_end":
      Redirect-To: "minecraft:overworld"
  Blacklisted-Biomes:
    # This will never let the player RTP into these biomes.
    - "minecraft:cold_ocean"
    - "minecraft:deep_cold_ocean"
    - "minecraft:deep_frozen_ocean"
    - "minecraft:deep_lukewarm_ocean"
    - "minecraft:deep_ocean"
    - "minecraft:frozen_ocean"
    - "minecraft:lukewarm_ocean"
    - "minecraft:ocean"
    - "minecraft:warm_ocean"
Unsafe-Blocks:
# These are used in multiple commands, such as RTP, Top, Ascend, and Descend.
# These commands will never let the player land on or in these blocks.
  - "minecraft:lava"
  - "minecraft:cactus"
  - "minecraft:bedrock"
Air-Blocks:
# These are the blocks that teleports will see as air.
  - "minecraft:air"
  - "minecraft:void_air"
  - "minecraft:cave_air"
Hat:
  # Items the player may not put on their head via /hat.
  Blacklisted-Items:
    - "minecraft:barrier" # This stops all barriers from being placed on the player's head.
    - "minecraft:diamond_sword:1" # This stops diamond swords with a CustomModelData of 1 from being put on the player's head.
Repair:
  # Items the player may not repair
  Blacklisted-Items:
    - "minecraft:wooden_axe"
    - "minecraft:wooden_axe:1"
# Migrate data from other mods into EEssentials
# By default, this will be off. Set to True to enable importing
Importers:
  EssentialCommands: false