# DON'T TOUCH Config-Version OR THINGS WILL BREAK
Config-Version: 1.1.0
# Disable/Enable Command Modules:
# Useful if you don't want a certain command on your server or if another mod handles a certain command
Commands:
  afk: true
  ascend: true
  back: true
  biomertp: true
  clearinventory: true
  hat: true
  home: true # Contains /home, /homes, /sethome, /delhome, /home:
  descend: true
  disposal: true
  enchant: true
  feed: true
  fly: true
  gm: true  # Contains /gma, /gmc, /gms, /gmsp
  godmode: true
  heal: true
  ignore: true
  itemeditor: true
  message: true # Contains /msg, /reply, /socialspy
  near: true
  playtime: true
  repair: true
  rtp: true
  seen: true
  smite: true
  spawn: true # Contains /spawn, /setspawn
  speed: true
  textcommands: true
  time: true
  tp: true # contains /tphere, /tpoffline
  tpa: true # Contains /tpa, /tpahere, /tpaccept, /tpdeny, /tpacancel
  top: true
  unalive: true
  warp: true # Contains /warp, /warps, /setwarp, /delwarp
  workstations: true # Contains anvil, cartography, enderchest, grindstone, loom, smithing, stonecutter, and workbench
AFK:
# Setting this to False will prevent any AFK-Notifications from being sent in chat
  Notifications: true
  # In Seconds
  AFK-Timer: 1800
  AFK-Kick-Timer: 3600
  # Command to run when a player is marked as AFK (leave empty if no command)
  AFK-Command: ""
Unsafe-Blocks:
# These are used in multiple commands, such as RTP, Top, Ascend, and Descend.
# These commands will never let the player land on or in these blocks.
  - "minecraft:lava"
  - "minecraft:cactus"
  - "minecraft:bedrock"
Air-Blocks:
# These are the blocks that teleports will see as air.
  - "minecraft:air"
  - "minecraft:void_air"
  - "minecraft:cave_air"
Hat:
  # Items the player may not put on their head via /hat.
  Blacklisted-Items:
    - "minecraft:barrier" # This stops all barriers from being placed on the player's head.
    - "minecraft:diamond_sword:1" # This stops diamond swords with a CustomModelData of 1 from being put on the player's head.
Repair:
  # Items the player may not repair
  Blacklisted-Items:
    - "minecraft:wooden_axe"
    - "minecraft:wooden_axe:1"
# Migrate data from other mods into EEssentials
# By default, this will be off. Set to True to enable importing
Importers:
  EssentialCommands: false